services:
  zabbix-postgres:
    image: postgres:16
    container_name: zabbix-postgres
    hostname: zabbix-postgres
    environment:
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "Abcd123"
    ports:
    - 8081:5432
    volumes:
    - zabbix-postgres-data:/var/lib/postgresql/data
    networks:
    - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    hostname: zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-postgres"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "Abcd123"
      POSTGRES_DB: "zabbix"
      ZBX_ENABLE_SNMP_TRAPS: true
    networks:
    - zabbix-network
    ports:
    - 10051:10051
    depends_on:
    - zabbix-postgres

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    hostname: zabbix-web
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "zabbix-postgres"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "Abcd123"
      POSTGRES_DB: "zabbix"
      PHP_TZ: "Asia/Karachi"
    networks:
    - zabbix-network
    ports:
    - 8080:8080
    depends_on:
    - zabbix-server

  zabbix-nginx:
    image: nginx
    container_name: zabbix-nginx
    hostname: zabbix-nginx
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    ports:
    - 80:80
    - 443:443
    depends_on:
    - zabbix-web
    networks:
    - zabbix-network


volumes:
  zabbix-postgres-data:

networks:
  zabbix-network:
    driver: bridge